In [14]:
import numpy as np
path = "data_set/datingTestSet.txt"

In [15]:
data = []
labels = []
open_file = open(path,mode = 'r',encoding = 'GBK')
STR = open_file.read()
lines = STR.split('\n')
for line in lines [0:200]:
    f_l = line.split('\t')
    x1,x2,x3,label = float(f_l[0]),float(f_l[1]),float(f_l[2]),f_l[3]
    data.append([x1,x2,x3])
    labels.append(label)
data = np.array(data)
labels = np.array(labels)
print(data)

[[4.0920000e+04 8.3269760e+00 9.5395200e-01]
 [1.4488000e+04 7.1534690e+00 1.6739040e+00]
 [2.6052000e+04 1.4418710e+00 8.0512400e-01]
 [7.5136000e+04 1.3147394e+01 4.2896400e-01]
 [3.8344000e+04 1.6697880e+00 1.3429600e-01]
 [7.2993000e+04 1.0141740e+01 1.0329550e+00]
 [3.5948000e+04 6.8307920e+00 1.2131920e+00]
 [4.2666000e+04 1.3276369e+01 5.4388000e-01]
 [6.7497000e+04 8.6315770e+00 7.4927800e-01]
 [3.5483000e+04 1.2273169e+01 1.5080530e+00]
 [5.0242000e+04 3.7234980e+00 8.3191700e-01]
 [6.3275000e+04 8.3858790e+00 1.6694850e+00]
 [5.5690000e+03 4.8754350e+00 7.2865800e-01]
 [5.1052000e+04 4.6800980e+00 6.2522400e-01]
 [7.7372000e+04 1.5299570e+01 3.3135100e-01]
 [4.3673000e+04 1.8894610e+00 1.9128300e-01]
 [6.1364000e+04 7.5167540e+00 1.2691640e+00]
 [6.9673000e+04 1.4239195e+01 2.6133300e-01]
 [1.5669000e+04 0.0000000e+00 1.2501850e+00]
 [2.8488000e+04 1.0528555e+01 1.3048440e+00]
 [6.4870000e+03 3.5402650e+00 8.2248300e-01]
 [3.7708000e+04 2.9915510e+00 8.3392000e-01]
 [2.262000

In [ ]:
max_ = np.max(data,axis=0)
min_ = np.min(data,axis=0)   #数据归一化

In [17]:
new_data = (data - min_) / (max_ - min_)

In [18]:
new_data

array([[0.52834087, 0.48692611, 0.56331011],
       [0.18706262, 0.41830442, 0.99080585],
       [0.33637185, 0.08431448, 0.47493847],
       [0.97012266, 0.76880364, 0.2515808 ],
       [0.4950807 , 0.09764209, 0.07661175],
       [0.9424532 , 0.59304578, 0.6102208 ],
       [0.46414461, 0.39943564, 0.71724259],
       [0.55088444, 0.77634554, 0.31981605],
       [0.87149128, 0.50473788, 0.44177803],
       [0.45814074, 0.71768268, 0.89232624],
       [0.64870239, 0.21773431, 0.49084772],
       [0.8169787 , 0.49037051, 0.98818192],
       [0.07190445, 0.28509469, 0.42953421],
       [0.65916075, 0.27367221, 0.36811679],
       [0.9989929 , 0.89465373, 0.19361979],
       [0.56388638, 0.11048764, 0.1104497 ],
       [0.79230471, 0.43954778, 0.75047785],
       [0.89958683, 0.83264751, 0.15204425],
       [0.20231117, 0.        , 0.73920843],
       [0.3678244 , 0.61566508, 0.77166405],
       [0.08375726, 0.20701963, 0.48524596],
       [0.48686895, 0.17493317, 0.49203706],
       [0.

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_test,y_train,y_test = train_test_split(new_data,labels,test_size=0.3,random_state=42)

In [33]:
def KNN_Model(train_data,y_train,test_data,y_test,K):
   
    predict_labels = []
    for test in test_data[0:4,...]:
        mins = train_data - test
        distance = np.power(np.sum(np.power(mins,2),axis=1),0.5)
        argsort = np.argsort(distance)[:K]
        labels = y_train[argsort]
        bin_labels = np.bincount(labels)
        predict = np.argmax(bin_labels)
        predict_labels.append(predict)
   
    PREDICT = np.array(predict_labels)
    
    acc = np.sum(np.equal(PREDICT,y_test[:4])) / PREDICT.size
    print('The test accuracy is :{} %'.format(acc * 100))

    
    

In [23]:
x_train.shape

(140, 3)

In [24]:
x_test.shape

(60, 3)

In [25]:
y_train.shape

(140,)

In [26]:
y_test.shape

(60,)

NameError: name 'show' is not defined